tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

tap "koekeishiya/formulae"
tap "cmacrae/formulae"

brew "cmacrae/formulae/spacebar"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

# This requires for libvterm -> vterm on emacs
brew "libtool"

# wireguard vpn
brew "wireguard-go"
brew "wireguard-tools"

cask "font-source-code-pro"
cask "iterm2"
# cask "alfred"
cask "qutebrowser"
# Scometime need to scan keycodes for mapping keyboard
# cash "key-codes"
