(("default"    . ((user-emacs-directory . "~/.emacs.d")))
 ("doom-emacs" . ((user-emacs-directory . "~/.config/doom-emacs")
                  (env . (("DOOMDIR" . "~/.config/doom")))))
 ("spacemacs"  . ((user-emacs-directory . "~/.config/spacemacs")))
 ("prelude"    . ((user-emacs-directory . "~/.config/prelude")))
 ("yay-evil-emacs"    . ((user-emacs-directory . "~/.config/yay-evil-emacs"))))
