#!/usr/bin/env bash

USAGE="$0 light|dark|light-medium|dark-medium|dark-pale"

TERMITE_CONF_FOLDER=~/.config/termite
THEME=$1

change_theme() {
    echo "# THIS FILE HAS BEEN AUTOGENERATED. DO NOT CHANGE MANUALLY!" | \
        cat - $TERMITE_CONF_FOLDER/config.base $TERMITE_CONF_FOLDER/themes/$1 > $TERMITE_CONF_FOLDER/config
    killall -USR1 termite || true
}

case $THEME in
    light|gruvbox-light) change_theme base16-gruvbox-light-soft.config  ;;
    light-medium|gruvbox-light-medium) change_theme base16-gruvbox-light-medium.config  ;;
    dark|gruvbox-dark) change_theme base16-gruvbox-dark-hard.config ;;
    dark-pale|gruvbox-dark-pale) change_theme base16-gruvbox-dark-pale.config ;;
    dark-medium|gruvbox-dark-medium) change_theme base16-gruvbox-dark-medium.config ;;
    *) echo $USAGE ;;
esac
