#!/usr/bin/env sh

# To restart: brew services restart spacebar

spacebar -m config position           bottom
spacebar -m config height             26
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config text_font          "Helvetica Neue:Bold:13.0"
spacebar -m config icon_font          "Monaco Nerd Font:Regular:13.0"
spacebar -m config background_color   0xff202020
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff458588
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip   ①  ②  ③  ④  ⑤  ⑥  ⑦  ⑧  ⑨  ⑩
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
#spacebar -m config clock_format       "%I:%M %p | %a, %b %e, %Y"
spacebar -m config clock_format       "%a, %b %e, %Y"
echo "spacebar configuration loaded.."
